### ISSUE TITLE
Lemonymous replace repair is broken. Source might be Board.IsTipImage

### ISSUE THREAD

**Issue by FeIix-E** [itb-community/ITB-ModLoader#150]
The if statement in the following code falsely returns true causing the board to be wiped:

![image](https://user-images.githubusercontent.com/98743718/184216962-80c49a64-f879-4151-92dc-7c587cd71cd4.png)

This is how Board.IsTipImage looks like:

![image](https://user-images.githubusercontent.com/98743718/184217303-299ca728-1501-4557-9e11-97caaed6fce2.png)

**Comment by KnightMiner** [comment]
`Lemon's LApi has its own definition of `IsTipImage`, and I am not sure whether it will win out our the mod loader one. Please verify if this bug happens without LApi (you can use `LOG` statements in a skill effect to do so).

That said, I already diiscussed with Lemonymous that there is a better way to handle the replace repair tip image part, using Subset's tip image logic instead of a hacky function.

**Comment by FeIix-E** [comment]
Lemon's LApi does indeed take precedence and forcing "replace repair" to use the modloaders version fixes all bugs with "replace repair".

Since the bug lies in Lemons LApi you can close this issue.
