### ISSUE TITLE
Add Event/Hook Stack Tracing Options

### ISSUE THREAD

**Issue by NamesAreHard6600** [itb-community/ITB-ModLoader#186]
Lemonymous said:

> Changing mod_loader/bootstrap/events.lua
line 106: sub.trace = debug.traceback()
line 206: LOG(sub.trace)
result:
```
An event callback failed:  No matching overload found, candidates:
BoardPawn* GetPawn(Board&,int)
BoardPawn* GetPawn(Board&,Point,bool)
BoardPawn* GetPawn(Board&,Point)
stack traceback:
    ./scripts/mod_loader/bootstrap/event.lua:106: in function 'subscribe'
    mods/TestMod/scripts/init.lua:12: in function 'init'
    ./scripts/mod_loader/mod_loader.lua:464: in function <./scripts/mod_loader/mod_loader.lua:462>
    [C]: in function 'xpcall'
    ./scripts/mod_loader/mod_loader.lua:461: in function 'initMod'
    ./scripts/mod_loader/mod_loader.lua:157: in function 'init'
    ./scripts/mod_loader/mod_loader.lua:781: in main chunk
    [C]: in function 'require'
    scripts/mod_loader/__scripts.lua:42: in main chunk
```
> It did identify my faulty subscription on line 12 in my test mod's init file.
So it is not that difficult, but should be an option rather than always on of course.

This would be a nice option to have, but probably shouldn't be always true. We could either 1. Connect it to development mode or 2. Create an option for it in the modloader settings. Or something else.

**Comment by kartoFlane** [comment]
Some time ago I toyed with rewriting the mod loader in TypeScript, and I did end up implementing tracing similar to this. Here's this functionality backported to lua: [event_traceable.zip](https://github.com/itb-community/ITB-ModLoader/files/10777556/event_traceable.zip) - replace the `event.lua` with the contents of this file, and it should identify the place in code where the failed event was dispatched, and where the subscription that failed was registered. Disclaimer: I didn't test this, so you might need to tweak it a little.

Generally I believe this sort of functionality should always be enabled, since when people report the problem to you, it's too late to enable it.

**Comment by NamesAreHard6600** [comment]
If we were to want it to happen at all times, (which is fair enough, maybe it defaults to on and there's an option to turn it off? Depends on if people really think that it is important to be able to turn it off), would what Lemon did not be a valid solution that wouldn't need much testing/tweaking?

**Comment by kartoFlane** [comment]
Both solutions are pretty simple, and don't change the file's workings too much; it's just a matter of verifying whether it works or not. Lemon's solution would only print information about the failed event dispatch, but not the failed subscription. That information can be inferred from the error's own stack trace, which is already logged, though it's somewhat less readable.

**Comment by Lemonymous** [comment]
Any update on this issue?

**Comment by kartoFlane** [comment]
Completed in #202 and released
